#!/bin/bash

touch /etc/cron.d/update-users
echo '*/15 *  *  *  * root /usr/local/bin/update-users' > /etc/cron.d/update-users

curl -L https://github.com/discourse-org/team-ssh-access/raw/master/update-users -o /usr/local/bin/update-users.new

if [[ $(wc -l </usr/local/bin/update-users.new) -ge 2 ]]
then
    mv /usr/local/bin/update-users.new /usr/local/bin/update-users
fi

chmod 0755 /usr/local/bin/update-users
/usr/local/bin/update-users

echo Done!
