#!/bin/bash
# https://github.com/discourse-org/team-ssh-access

curl -L https://github.com/discourse-org/team-ssh-access/raw/master/authorized_keys -o /root/.ssh/authorized_keys.new

if [[ $(wc -l </root/.ssh/authorized_keys.new) -ge 2 ]]
then
    mv /root/.ssh/authorized_keys.new /root/.ssh/authorized_keys
fi
